[mypy]
python_version = 3.11
strict = false
warn_return_any = false
warn_unused_configs = false
disallow_untyped_defs = false
ignore_missing_imports = true
check_untyped_defs = true

[mypy-tests.*]
ignore_errors = true
